services:
  - type: web
    name: foodiemap-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true

databases:
  - name: foodiemap-mongodb
    type: mongodb
    version: "6.0"